version: "3.9"

services:
  backend:
    ports:
      - 8000:8000
    build: 
      context: ./backend
      args:
        - DEV=true
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  frontend:
    ports:
      - 3000:3000
    build:
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app 
